"""
Full-text search router.

GET /api/search?q=work+permit&limit=10&offset=0

Uses Python-side TF-IDF-style scoring over a comprehensive in-process
index (31 modules + 10 blog posts + 20 static pages + 8 tool pages).
No external search engine required.

Scoring algorithm:
  - Exact phrase match in title              → 8 pts
  - Exact phrase match in description        → 4 pts
  - Exact phrase match in keywords           → 6 pts
  - Each individual query token in title     → 3 pts each
  - Each individual query token in descr.    → 1 pt each
  - Each individual query token in keywords  → 2 pts each
  - Prefix match on tokens (partial)         → 0.5 pt each occurrence
  - Type boost: module > blog > tool > page

Score is then normalised to a 0–1 range and a highlighted snippet is
generated by bolding the first occurrence of each matched token.
"""

from __future__ import annotations

import re
from typing import Annotated, Literal

from fastapi import APIRouter, Query, Request
from pydantic import BaseModel, Field

from app.middleware.rate_limit import limiter

router = APIRouter(prefix="/api/search", tags=["search"])

# ---------------------------------------------------------------------------
# Type alias for result type literals
# ---------------------------------------------------------------------------

ResultType = Literal["module", "blog", "tool", "page"]

# ---------------------------------------------------------------------------
# Search index — single source of truth for all searchable content
# ---------------------------------------------------------------------------

# Type alias: each index entry is a plain dict keyed by string
_IndexEntry = dict[str, object]

_RAW_INDEX: list[_IndexEntry] = [
    # ── FREE MODULES ─────────────────────────────────────────────────────────
    {
        "id": "free-01",
        "title": "Complete Guide to the Swiss Immigration System",
        "description": (
            "A comprehensive introduction to Switzerland's immigration framework. "
            "Covers the complete legal foundations, all residence permit categories, "
            "entry requirements, and practical pathways for foreign nationals seeking "
            "to establish residence and employment in Switzerland."
        ),
        "url": "/modules/free-01",
        "type": "module",
        "keywords": [
            "immigration system", "swiss immigration", "residence permit",
            "entry requirements", "EU EFTA", "third-country", "FMPA",
            "foreign nationals", "cantons",
        ],
    },
    {
        "id": "free-02",
        "title": "Application Process: Documentation and Timelines",
        "description": (
            "Detailed procedural guide covering all documentation requirements, "
            "realistic processing timelines, common application pitfalls, and proven "
            "strategies for successful residence permit applications in Switzerland."
        ),
        "url": "/modules/free-02",
        "type": "module",
        "keywords": [
            "application", "documentation", "timeline", "processing time",
            "residence permit", "passport", "health insurance", "commune registration",
            "employer", "work permit application",
        ],
    },
    {
        "id": "free-03",
        "title": "Integration Requirements and Swiss Society",
        "description": (
            "Understanding integration as both a legal requirement and practical "
            "necessity in Switzerland. Covers language proficiency standards, "
            "economic participation requirements, and guidance for establishing "
            "yourself within Swiss society."
        ),
        "url": "/modules/free-03",
        "type": "module",
        "keywords": [
            "integration", "language", "society", "quota", "B permit", "C permit",
            "permanent residence", "A2", "B1",
        ],
    },
    # ── IMMIGRATION PACK MODULES ─────────────────────────────────────────────
    {
        "id": "imm-01",
        "title": "Swiss CV Template and Formatting",
        "description": (
            "Master the Swiss CV format with comprehensive templates, formatting "
            "guidelines, cultural insights, and proven strategies. Learn how Swiss "
            "employers evaluate CVs, what to include, what to exclude, and how to "
            "optimise your CV for maximum impact in the Swiss job market."
        ),
        "url": "/modules/imm-01",
        "type": "module",
        "keywords": [
            "cv", "resume", "curriculum vitae", "swiss cv", "template", "format",
            "job market", "employers", "photo", "ATS",
        ],
    },
    {
        "id": "imm-02",
        "title": "Swiss Cover Letter Mastery",
        "description": (
            "Master writing compelling Swiss cover letters (Bewerbungsschreiben) "
            "that get results. Learn Swiss professional communication standards, "
            "cultural nuances, legal compliance requirements, and proven frameworks "
            "that increase application success rates in the Swiss job market."
        ),
        "url": "/modules/imm-02",
        "type": "module",
        "keywords": [
            "cover letter", "Bewerbungsschreiben", "application letter",
            "professional communication", "job application", "motivation letter",
        ],
    },
    {
        "id": "imm-03",
        "title": "Swiss CV Templates and Interactive Builder",
        "description": (
            "Access comprehensive Swiss CV templates for every career level and "
            "industry. Includes ready-to-use formats with real example content, "
            "ATS optimisation checklist, and sector-specific templates for tech, "
            "finance, pharma, and consulting."
        ),
        "url": "/modules/imm-03",
        "type": "module",
        "keywords": [
            "cv template", "cv builder", "resume template", "ATS", "career",
            "tech", "finance", "pharma", "consulting", "cv format",
        ],
    },
    {
        "id": "imm-04",
        "title": "Swiss Salary Benchmarks and Negotiation",
        "description": (
            "Comprehensive salary analysis across all industries, cantons, and "
            "experience levels. Master salary negotiation strategies, understand "
            "total compensation packages, and maximise your earning potential in "
            "the Swiss job market with data-driven insights based on official SECO data."
        ),
        "url": "/modules/imm-04",
        "type": "module",
        "keywords": [
            "salary", "salary negotiation", "compensation", "SECO", "wages",
            "median salary", "Zug", "13th month", "bonus", "CHF", "pay",
        ],
    },
    {
        "id": "imm-05",
        "title": "Embassy Submission Guide",
        "description": (
            "Master the embassy submission process with comprehensive checklists, "
            "document preparation guides, appointment scheduling, and step-by-step "
            "procedures for successful permit collection at Swiss embassies and "
            "consulates worldwide."
        ),
        "url": "/modules/imm-05",
        "type": "module",
        "keywords": [
            "embassy", "consulate", "submission", "visa appointment", "permit collection",
            "entry", "arrival", "registration", "commune",
        ],
    },
    {
        "id": "imm-06",
        "title": "Finding Work in Switzerland",
        "description": (
            "Master the Swiss job market with proven strategies, official platforms, "
            "networking approaches, and employer outreach. Covers job-room.ch, LinkedIn, "
            "recruitment agencies, Swiss business etiquette, application timing, and "
            "what employers look for."
        ),
        "url": "/modules/imm-06",
        "type": "module",
        "keywords": [
            "job search", "employment", "job-room.ch", "LinkedIn", "recruitment",
            "networking", "Vitamin B", "Beziehungen", "Probezeit", "probation",
            "quota timing",
        ],
    },
    {
        "id": "imm-07",
        "title": "Health Insurance and Your First 30 Days",
        "description": (
            "Everything you need when you first arrive in Switzerland: mandatory "
            "commune registration within 14 days, Swiss health insurance (KVG) within "
            "3 months, opening a bank account, transport and mobile setup, finding "
            "housing, and essential services like AHV."
        ),
        "url": "/modules/imm-07",
        "type": "module",
        "keywords": [
            "health insurance", "KVG", "Krankenversicherung", "arrival", "first days",
            "registration", "commune", "bank account", "AHV", "housing", "priminfo",
        ],
    },
    {
        "id": "imm-08",
        "title": "Understanding Swiss Workplace Culture",
        "description": (
            "Navigate Swiss professional norms, expectations, communication style, "
            "and etiquette. Learn work-life balance expectations, regional differences, "
            "employment law essentials, and how to avoid common mistakes so you can "
            "integrate successfully into the Swiss workplace."
        ),
        "url": "/modules/imm-08",
        "type": "module",
        "keywords": [
            "workplace culture", "Swiss culture", "punctuality", "Probezeit",
            "Arbeitszeugnis", "reference letter", "Ruhezeiten", "quiet hours",
            "professional norms",
        ],
    },
    # ── ADVANCED PACK MODULES ────────────────────────────────────────────────
    {
        "id": "adv-01",
        "title": "Beat the Non-EU Quota System",
        "description": (
            "Master strategic approaches to navigate Switzerland's strict annual "
            "quota system for non-EU/EFTA nationals. Learn quota management, timing "
            "optimisation, exception categories, and proven methods to maximise your "
            "chances within the competitive 8,500 annual permit allocation."
        ),
        "url": "/modules/adv-01",
        "type": "module",
        "keywords": [
            "quota", "non-EU", "annual quota", "8500", "permit quota", "quota system",
            "third-country", "exception", "researcher", "specialist",
        ],
    },
    {
        "id": "adv-02",
        "title": "Employer Motivation Letters",
        "description": (
            "Master employer motivation letters for Swiss work permit applications. "
            "Full letter templates for tech, finance, pharma, and consulting sectors. "
            "Includes mandatory legal content checklist, canton-specific preferences, "
            "and common rejection pitfalls based on LEI Art. 23 and OASA Art. 15-22."
        ),
        "url": "/modules/adv-02",
        "type": "module",
        "keywords": [
            "employer letter", "motivation letter", "work permit letter",
            "Inländervorrang", "labor market test", "LEI", "OASA", "rejection",
        ],
    },
    {
        "id": "adv-03",
        "title": "Cantonal Immigration Variations",
        "description": (
            "Master cantonal variations in Swiss immigration processing. Comprehensive "
            "analysis of all 26 cantons, their success rates, requirements, processing "
            "times, and strategic selection criteria. Learn how choosing the right "
            "canton can multiply your approval chances 2-3x."
        ),
        "url": "/modules/adv-03",
        "type": "module",
        "keywords": [
            "canton", "cantonal", "26 cantons", "Zurich", "Geneva", "Basel",
            "approval rate", "processing time", "canton selection", "success rate",
        ],
    },
    {
        "id": "adv-04",
        "title": "Swiss Tax and Financial Planning",
        "description": (
            "Master the Swiss tax system, optimise your financial planning, and "
            "maximise wealth building in Switzerland. Comprehensive guide to federal "
            "and cantonal taxes, Pillar 2 and 3a pension optimisation, investment "
            "strategies, and financial planning. Includes 2025 tax tables."
        ),
        "url": "/modules/adv-04",
        "type": "module",
        "keywords": [
            "tax", "taxes", "Quellensteuer", "withholding tax", "Pillar 3a",
            "Pillar 2", "BVG", "pension", "Zug tax", "cantonal tax", "income tax",
        ],
    },
    {
        "id": "adv-05",
        "title": "Swiss Language Requirements and Test Preparation",
        "description": (
            "Master Swiss language requirements for work permits, residence, and "
            "citizenship. Comprehensive guide to German, French, and Italian "
            "proficiency levels, test preparation strategies, certification options, "
            "and proven study frameworks for B1/B2 requirements."
        ),
        "url": "/modules/adv-05",
        "type": "module",
        "keywords": [
            "language", "language test", "German", "French", "Italian", "B1", "B2",
            "fide", "Goethe", "DELF", "CEFR", "language requirement", "Swiss German",
        ],
    },
    {
        "id": "adv-06",
        "title": "Swiss Integration and Social Adaptation",
        "description": (
            "Master Swiss integration requirements for work permits, residence permits, "
            "and citizenship. Comprehensive guide to integration criteria, language "
            "proficiency, economic participation, social adaptation, integration "
            "agreements, and proven strategies based on LEI Art. 58a and OASA Art. 62."
        ),
        "url": "/modules/adv-06",
        "type": "module",
        "keywords": [
            "integration", "social adaptation", "Integrationsvereinbarung",
            "integration agreement", "LEI", "OASA", "economic participation",
            "community",
        ],
    },
    {
        "id": "adv-07",
        "title": "Swiss Healthcare and Insurance System",
        "description": (
            "Master Switzerland's mandatory healthcare system, understand KVG "
            "requirements, navigate insurance selection, and optimise costs. "
            "Comprehensive guide to health insurance models, premium optimisation, "
            "coverage options, and healthcare system navigation."
        ),
        "url": "/modules/adv-07",
        "type": "module",
        "keywords": [
            "healthcare", "KVG", "health insurance", "franchise", "deductible",
            "HMO", "Telemed", "premium", "comparis", "Krankenkasse",
        ],
    },
    {
        "id": "adv-08",
        "title": "Swiss Housing and Cost of Living",
        "description": (
            "Master Swiss rental markets, housing requirements, cost of living, and "
            "practical living expenses. Comprehensive guide to finding housing, rental "
            "contracts, deposits, utilities, living costs by canton, and budgeting "
            "strategies. Includes rental law and housing documentation requirements."
        ),
        "url": "/modules/adv-08",
        "type": "module",
        "keywords": [
            "housing", "rental", "apartment", "Betreibungsauszug", "deposit",
            "Kaution", "cost of living", "rent", "Zurich", "budget", "landlord",
        ],
    },
    {
        "id": "adv-09",
        "title": "Swiss Family Reunification",
        "description": (
            "Master the Swiss family reunification process, understand legal "
            "requirements, prepare comprehensive applications, and successfully reunite "
            "with family members. Covers eligibility, documentation, application "
            "procedures, timelines, and LEI Art. 44-46, OASA Art. 42-47."
        ),
        "url": "/modules/adv-09",
        "type": "module",
        "keywords": [
            "family reunification", "spouse", "children", "dependents", "LEI",
            "OASA", "family permit", "housing requirement", "income requirement",
        ],
    },
    {
        "id": "adv-10",
        "title": "Success Stories and Lessons Learned",
        "description": (
            "Learn from successful Swiss immigrants who navigated the system "
            "effectively. Comprehensive collection of real-world success stories, "
            "proven strategies, common mistakes to avoid, and actionable lessons "
            "learned across different nationalities, industries, and permit types."
        ),
        "url": "/modules/adv-10",
        "type": "module",
        "keywords": [
            "success story", "case study", "lessons", "rejection", "appeal",
            "Einsprache", "Recours", "mistakes", "strategies",
        ],
    },
    # ── CITIZENSHIP PACK MODULES ─────────────────────────────────────────────
    {
        "id": "cit-01",
        "title": "10-Year Path to Swiss Citizenship",
        "description": (
            "Master the complete 10-year journey from first arrival to Swiss "
            "citizenship. Comprehensive guide to permit progression (L → B → C), "
            "year-by-year milestones, cantonal comparison for strategic residence "
            "planning, and detailed application preparation under LN Art. 9-19."
        ),
        "url": "/modules/cit-01",
        "type": "module",
        "keywords": [
            "citizenship", "naturalization", "10 years", "LN", "permit progression",
            "L permit", "B permit", "C permit", "milestones", "residency calculation",
        ],
    },
    {
        "id": "cit-02",
        "title": "Spouse Route to Swiss Citizenship",
        "description": (
            "Master the facilitated naturalization pathway for spouses of Swiss "
            "citizens, reducing the citizenship timeline from 10 years to 5 years. "
            "Covers LN Art. 21 (spouse in Switzerland), LN Art. 22 (spouse abroad), "
            "union conjugale assessment, and SEM application procedure."
        ),
        "url": "/modules/cit-02",
        "type": "module",
        "keywords": [
            "spouse", "marriage", "facilitated naturalization", "simplified",
            "5 years", "union conjugale", "LN Art 21", "Swiss spouse",
        ],
    },
    {
        "id": "cit-03",
        "title": "Third-Generation Accelerated Path",
        "description": (
            "Master the accelerated naturalization pathway for third-generation "
            "immigrants born in Switzerland. Covers LN Art. 24-26 eligibility "
            "(must be under 25), parent and grandparent residence requirements, "
            "complete document checklist, and application procedure."
        ),
        "url": "/modules/cit-03",
        "type": "module",
        "keywords": [
            "third generation", "born in Switzerland", "grandparent", "LN Art 24",
            "accelerated", "under 25", "compulsory schooling",
        ],
    },
    {
        "id": "cit-04",
        "title": "Language Test Mastery: B1 Certification",
        "description": (
            "Master Swiss language requirements for citizenship: understand OLN Art. 6 "
            "requirements, choose the right test (fide, Goethe, DELF, telc, TestDaF), "
            "prepare with proven strategies, and understand certificate equivalency. "
            "Includes a 12-week preparation plan."
        ),
        "url": "/modules/cit-04",
        "type": "module",
        "keywords": [
            "B1 certification", "language test", "fide", "Goethe", "DELF", "telc",
            "TestDaF", "OLN", "B1 speaking", "A2 writing", "language certificate",
        ],
    },
    {
        "id": "cit-05",
        "title": "Integration Test Success",
        "description": (
            "Master cantonal integration tests and naturalization interviews, "
            "understand test formats, prepare comprehensively, and pass on first "
            "attempt. Comprehensive guide to Swiss history, politics, geography, "
            "and proven success strategies."
        ),
        "url": "/modules/cit-05",
        "type": "module",
        "keywords": [
            "integration test", "naturalization interview", "Swiss history",
            "Swiss politics", "Volksinitiative", "Federal Council", "canton",
            "direct democracy", "referendum",
        ],
    },
    {
        "id": "cit-06",
        "title": "Citizenship Application Submission",
        "description": (
            "Master the complete citizenship application submission process from "
            "document assembly to final filing. Covers all required documents, "
            "cantonal fee tables for all 26 cantons, the three-level submission "
            "procedure (commune → canton → SEM), and common rejection reasons."
        ),
        "url": "/modules/cit-06",
        "type": "module",
        "keywords": [
            "citizenship application", "submission", "commune", "SEM",
            "three levels", "fees", "naturalization fees", "LN Art 13",
            "processing time",
        ],
    },
    {
        "id": "cit-07",
        "title": "Naturalization Interview Preparation",
        "description": (
            "Master naturalization interview preparation with 30+ real sample "
            "questions by category (Swiss history, politics, geography, culture, "
            "daily life), model answers, canton-specific variations, scoring "
            "criteria, and a 6-week preparation plan."
        ),
        "url": "/modules/cit-07",
        "type": "module",
        "keywords": [
            "interview", "naturalization interview", "sample questions", "history",
            "politics", "commune", "mayor", "local knowledge", "preparation",
        ],
    },
    {
        "id": "cit-08",
        "title": "Dual Citizenship Strategy",
        "description": (
            "Master Swiss dual citizenship policies with a comprehensive 30+ country "
            "policy table, renunciation procedures by country, tax implications of "
            "holding multiple citizenships, military service obligations, and "
            "strategic planning for citizenship retention."
        ),
        "url": "/modules/cit-08",
        "type": "module",
        "keywords": [
            "dual citizenship", "dual nationality", "renunciation", "tax", "military",
            "two passports", "multiple citizenship", "home country",
        ],
    },
    {
        "id": "cit-09",
        "title": "Facilitated Naturalization and Special Cases",
        "description": (
            "Master the facilitated naturalization paths: spouse of a Swiss citizen "
            "(LN Art. 21-22), third-generation foreigners (LN Art. 24-25), former "
            "Swiss citizens seeking reintegration (LN Art. 27-29), and stateless "
            "persons (LN Art. 23). Includes eligibility criteria and canton differences."
        ),
        "url": "/modules/cit-09",
        "type": "module",
        "keywords": [
            "facilitated naturalization", "simplified naturalization", "special cases",
            "stateless", "reintegration", "LN Art 27", "LN Art 24", "LN Art 21",
        ],
    },
    {
        "id": "cit-10",
        "title": "Oath Ceremony and Becoming Swiss",
        "description": (
            "Master the final steps to Swiss citizenship: oath ceremony procedures "
            "by language region, post-naturalization checklist (passport, military "
            "registration, AHV, voting), full breakdown of citizenship rights and "
            "obligations, and Swiss passport application guide."
        ),
        "url": "/modules/cit-10",
        "type": "module",
        "keywords": [
            "oath", "oath ceremony", "Swiss passport", "naturalization decree",
            "voting rights", "military", "AHV", "post-citizenship", "becoming Swiss",
        ],
    },
    # ── WORK PERMITS (bonus module) ──────────────────────────────────────────
    {
        "id": "work-permits",
        "title": "Work Permit Application Guide",
        "description": (
            "Comprehensive guide to applying for a Swiss work permit. Covers the "
            "complete work permit application process, required documents, employer "
            "responsibilities, cantonal variations, quota management, and step-by-step "
            "procedures for both EU/EFTA and non-EU/EFTA applicants."
        ),
        "url": "/modules/work-permits",
        "type": "module",
        "keywords": [
            "work permit", "working permit", "employment permit", "employer",
            "quota", "EU EFTA", "non-EU", "cantonal", "document checklist",
        ],
    },
    # ── BLOG POSTS ───────────────────────────────────────────────────────────
    {
        "id": "blog-language-requirements",
        "title": "Language Requirements for Swiss Immigration: From A1 to C1",
        "description": (
            "Complete guide to Swiss language requirements for permits, citizenship, "
            "and integration. Required levels, recognised tests, study timelines, "
            "and immersion strategies."
        ),
        "url": "/blog/language-requirements-a1-to-c1",
        "type": "blog",
        "keywords": [
            "language", "A1", "A2", "B1", "B2", "C1", "language requirement",
            "German", "French", "Italian", "fide", "CEFR", "language level",
        ],
    },
    {
        "id": "blog-cost-of-living",
        "title": "Cost of Living in Major Swiss Cities: Complete 2026 Guide",
        "description": (
            "Detailed breakdown of living costs in Zurich, Geneva, Basel, Bern, and "
            "Lausanne. Housing, food, transport, and total monthly budgets."
        ),
        "url": "/blog/cost-of-living-swiss-cities-2026",
        "type": "blog",
        "keywords": [
            "cost of living", "Zurich", "Geneva", "Basel", "Bern", "Lausanne",
            "housing cost", "rent", "food", "transport", "monthly budget",
        ],
    },
    {
        "id": "blog-family-reunification",
        "title": "Family Reunification in Switzerland: Step-by-Step Process Guide",
        "description": (
            "Complete guide to bringing your family to Switzerland. Income thresholds, "
            "housing requirements, document checklists, and cantonal timelines."
        ),
        "url": "/blog/family-reunification-step-by-step-process",
        "type": "blog",
        "keywords": [
            "family reunification", "spouse", "children", "income threshold",
            "housing", "cantonal", "document checklist",
        ],
    },
    {
        "id": "blog-cv-format",
        "title": "CV Format for Swiss Employers: ATS Optimisation Guide",
        "description": (
            "Format your CV for Swiss employers and ATS systems. Photo requirements, "
            "Swiss-specific sections, keyword optimisation, and industry templates."
        ),
        "url": "/blog/cv-format-swiss-employers-ats-optimization",
        "type": "blog",
        "keywords": [
            "cv format", "ATS", "resume", "Swiss employers", "photo", "keyword",
            "industry template",
        ],
    },
    {
        "id": "blog-salary-negotiation",
        "title": "Salary Negotiation in Switzerland: Cultural Insights and Strategies",
        "description": (
            "Master salary negotiation with Swiss cultural awareness. Ranges by "
            "industry and canton, negotiation scripts, and total compensation strategies."
        ),
        "url": "/blog/salary-negotiation-switzerland-cultural-insights",
        "type": "blog",
        "keywords": [
            "salary negotiation", "compensation", "Swiss culture", "salary range",
            "industry", "canton", "negotiation",
        ],
    },
    {
        "id": "blog-cantonal-variations",
        "title": "Understanding Swiss Cantonal Variations: How 26 Cantons Shape Your Application",
        "description": (
            "Approval rates, processing times, salary minimums, and housing rules "
            "across Swiss cantons. Data-driven strategies for choosing the right canton."
        ),
        "url": "/blog/understanding-swiss-cantonal-variations",
        "type": "blog",
        "keywords": [
            "cantonal variations", "26 cantons", "approval rate", "processing time",
            "salary minimum", "canton selection",
        ],
    },
    {
        "id": "blog-common-mistakes",
        "title": "10 Common Mistakes in Swiss Work Permit Applications",
        "description": (
            "After analysing thousands of applications, here are the most frequent "
            "mistakes that lead to rejection — and exactly how to avoid each one."
        ),
        "url": "/blog/10-common-mistakes-work-permit-applications",
        "type": "blog",
        "keywords": [
            "mistakes", "rejection", "work permit", "application errors",
            "common errors", "avoid rejection",
        ],
    },
    {
        "id": "blog-l-permit",
        "title": "Complete Guide to Swiss L Permit (Short-term Residence)",
        "description": (
            "Everything about the L permit: requirements, application process, "
            "quota system, renewal rules, and tips for a successful application."
        ),
        "url": "/blog/swiss-l-permit-guide",
        "type": "blog",
        "keywords": [
            "L permit", "short-term residence", "L permit requirements",
            "L permit renewal", "quota",
        ],
    },
    {
        "id": "blog-b-permit",
        "title": "Swiss B Permit: The Definitive Guide to Long-term Residence",
        "description": (
            "EU vs non-EU pathways, quotas, cantonal processing differences, family "
            "reunification, path to C permit, costs, and employment change rules."
        ),
        "url": "/blog/swiss-b-permit-complete-guide",
        "type": "blog",
        "keywords": [
            "B permit", "long-term residence", "B permit EU", "B permit non-EU",
            "quota", "family reunification", "C permit path",
        ],
    },
    {
        "id": "blog-citizenship",
        "title": "Swiss Citizenship: Complete Naturalization Guide",
        "description": (
            "Three-level naturalization explained: federal, cantonal, and municipal. "
            "Language tests, integration interviews, costs by canton, and success tips."
        ),
        "url": "/blog/swiss-citizenship-guide",
        "type": "blog",
        "keywords": [
            "citizenship", "naturalization", "federal", "cantonal", "municipal",
            "language test", "integration interview",
        ],
    },
    # ── TOOL PAGES ───────────────────────────────────────────────────────────
    {
        "id": "tool-permit-calculator",
        "title": "Permit Eligibility Calculator",
        "description": (
            "Determine which Swiss residence permit you qualify for based on your "
            "nationality, employment situation, and planned duration of stay."
        ),
        "url": "/tools/permit-calculator",
        "type": "tool",
        "keywords": [
            "permit calculator", "eligibility", "which permit", "permit checker",
            "nationality", "employment",
        ],
    },
    {
        "id": "tool-cv-builder",
        "title": "Swiss CV Builder",
        "description": (
            "Create a professional Swiss-format CV in minutes with our interactive "
            "builder. 15 templates covering all industries and career levels."
        ),
        "url": "/tools/cv-editor",
        "type": "tool",
        "keywords": [
            "cv builder", "resume builder", "Swiss CV", "cv generator",
            "cv template", "CV editor",
        ],
    },
    {
        "id": "tool-timeline-planner",
        "title": "Immigration Timeline Planner",
        "description": (
            "Plan your entire Swiss immigration journey with a personalised timeline. "
            "Input your situation and get a month-by-month action plan."
        ),
        "url": "/tools/timeline-planner",
        "type": "tool",
        "keywords": [
            "timeline", "planner", "immigration plan", "action plan",
            "month by month", "schedule",
        ],
    },
    {
        "id": "tool-citizenship-timeline",
        "title": "Citizenship Timeline Calculator",
        "description": (
            "Calculate exactly when you will become eligible for Swiss citizenship "
            "based on your arrival date, permit history, and residence type."
        ),
        "url": "/tools/citizenship-timeline",
        "type": "tool",
        "keywords": [
            "citizenship timeline", "naturalization date", "eligibility date",
            "10 years", "citizenship calculator",
        ],
    },
    {
        "id": "tool-dossier-generator",
        "title": "Application Dossier Generator",
        "description": (
            "Generate a personalised Swiss permit application dossier with the "
            "exact documents required for your situation, pre-filled templates, "
            "and a submission checklist."
        ),
        "url": "/tools/dossier-generator",
        "type": "tool",
        "keywords": [
            "dossier", "application package", "document generator", "checklist",
            "templates", "permit application",
        ],
    },
    # ── STATIC / INFO PAGES ──────────────────────────────────────────────────
    {
        "id": "page-visas",
        "title": "Visa Types and Residence Permits",
        "description": (
            "Complete guide to all Swiss visa types and residence permits: L permit "
            "(short-term), B permit (annual), C permit (permanent), G permit "
            "(cross-border), student visas, asylum, and special categories."
        ),
        "url": "/visas",
        "type": "page",
        "keywords": [
            "visa", "permit", "L permit", "B permit", "C permit", "G permit",
            "student visa", "Schengen", "national visa", "D visa",
        ],
    },
    {
        "id": "page-employment",
        "title": "Employment Hub",
        "description": (
            "Everything about working in Switzerland: job market overview, salary "
            "benchmarks, employment quotas, work permit requirements, and career "
            "resources for foreign nationals."
        ),
        "url": "/employment",
        "type": "page",
        "keywords": [
            "employment", "job", "work", "job market", "quota", "salary",
            "career", "Swiss employer",
        ],
    },
    {
        "id": "page-citizenship",
        "title": "Citizenship Pathways",
        "description": (
            "Swiss naturalization guide covering ordinary naturalization (10 years), "
            "facilitated naturalization for spouses, third-generation path, and "
            "citizenship reinstatement."
        ),
        "url": "/citizenship",
        "type": "page",
        "keywords": [
            "citizenship", "naturalization", "Swiss passport", "10 years",
            "facilitated", "spouse route",
        ],
    },
    {
        "id": "page-cantons",
        "title": "Canton Information Centre",
        "description": (
            "Comprehensive information on all 26 Swiss cantons: immigration success "
            "rates, salary thresholds, processing times, language requirements, "
            "and strategic selection guidance."
        ),
        "url": "/cantons",
        "type": "page",
        "keywords": [
            "canton", "26 cantons", "Zurich", "Geneva", "Bern", "Basel",
            "Zug", "Vaud", "cantonal information",
        ],
    },
    {
        "id": "page-cv-templates",
        "title": "CV Templates for Switzerland",
        "description": (
            "15 professional Swiss CV templates covering all industries. Download "
            "ready-to-use formats for tech, finance, pharma, hospitality, and more."
        ),
        "url": "/cv-templates",
        "type": "page",
        "keywords": [
            "cv template", "resume template", "Swiss CV", "download",
            "professional template",
        ],
    },
    {
        "id": "page-pricing",
        "title": "Pricing Plans",
        "description": (
            "Subscription plans starting from free. Choose from Immigration Pack "
            "(CHF 9/mo), Advanced Pack (CHF 29/mo), and Citizenship Pro (CHF 79/mo). "
            "One-time products also available."
        ),
        "url": "/pricing",
        "type": "page",
        "keywords": [
            "pricing", "plan", "subscription", "cost", "CHF", "free plan",
            "immigration pack", "advanced pack", "citizenship pro",
        ],
    },
    {
        "id": "page-resources",
        "title": "Resources and Downloads",
        "description": (
            "Free and premium Swiss immigration resources: document checklists, "
            "permit application templates, integration guides, and PDF downloads."
        ),
        "url": "/resources",
        "type": "page",
        "keywords": [
            "resources", "download", "template", "checklist", "guide", "PDF",
            "document",
        ],
    },
    {
        "id": "page-faq",
        "title": "Frequently Asked Questions",
        "description": (
            "Answers to the most common Swiss immigration questions: permit types, "
            "processing times, language requirements, citizenship eligibility, and more."
        ),
        "url": "/faq",
        "type": "page",
        "keywords": [
            "FAQ", "frequently asked", "questions", "help", "how to",
            "common questions",
        ],
    },
    {
        "id": "page-consultation",
        "title": "Book an Immigration Consultation",
        "description": (
            "Schedule a personalised immigration consultation with a Swiss immigration "
            "expert. 30-minute quick consultation (CHF 80) or full 90-minute session "
            "(CHF 200)."
        ),
        "url": "/consultation",
        "type": "page",
        "keywords": [
            "consultation", "expert", "lawyer", "advice", "book", "appointment",
            "immigration expert", "CHF 80", "CHF 200",
        ],
    },
    {
        "id": "page-marketplace",
        "title": "Lawyer and Agency Marketplace",
        "description": (
            "Find verified Swiss immigration lawyers, relocation agencies, and "
            "specialists. Read reviews, compare services, and book directly through "
            "the platform."
        ),
        "url": "/marketplace",
        "type": "page",
        "keywords": [
            "lawyer", "agency", "marketplace", "specialist", "relocation",
            "immigration lawyer", "find lawyer",
        ],
    },
    {
        "id": "page-b2b",
        "title": "Corporate Immigration Portal",
        "description": (
            "B2B immigration management platform for companies relocating employees "
            "to Switzerland. Automate compliance, track permits, and manage your "
            "mobile workforce."
        ),
        "url": "/b2b",
        "type": "page",
        "keywords": [
            "B2B", "corporate", "company", "employer", "relocation", "HR",
            "compliance", "workforce mobility",
        ],
    },
    {
        "id": "page-dashboard",
        "title": "Your Learning Dashboard",
        "description": (
            "Access your personalised immigration learning dashboard. Track module "
            "progress, download resources, view your permit status, and pick up "
            "where you left off."
        ),
        "url": "/dashboard",
        "type": "page",
        "keywords": [
            "dashboard", "account", "profile", "progress", "modules", "learning",
        ],
    },
    {
        "id": "page-about",
        "title": "About Swiss Immigration Pro",
        "description": (
            "Learn about the team behind Swiss Immigration Pro, our mission to "
            "simplify Swiss immigration, and how we help thousands of people "
            "successfully relocate to Switzerland."
        ),
        "url": "/about",
        "type": "page",
        "keywords": ["about", "team", "mission", "company", "who we are"],
    },
    {
        "id": "page-contact",
        "title": "Contact Us",
        "description": (
            "Get in touch with the Swiss Immigration Pro team. We respond to all "
            "enquiries within 24 hours."
        ),
        "url": "/contact",
        "type": "page",
        "keywords": ["contact", "support", "email", "help", "get in touch"],
    },
]

# ---------------------------------------------------------------------------
# Type-priority boosts (applied as additive score points)
# ---------------------------------------------------------------------------

_TYPE_BOOST: dict[str, float] = {
    "module": 2.0,
    "blog": 1.0,
    "tool": 1.5,
    "page": 0.0,
}

# ---------------------------------------------------------------------------
# Pre-processing helpers
# ---------------------------------------------------------------------------

_STOPWORDS: frozenset[str] = frozenset(
    {
        "a", "an", "the", "and", "or", "but", "in", "on", "at", "to", "for",
        "of", "with", "by", "from", "is", "are", "was", "were", "be", "been",
        "being", "have", "has", "had", "do", "does", "did", "will", "would",
        "could", "should", "may", "might", "shall", "can", "i", "you", "he",
        "she", "it", "we", "they", "me", "him", "her", "us", "them",
    }
)


def _normalise(text: str) -> str:
    """Lower-case and strip punctuation."""
    return re.sub(r"[^\w\s]", " ", text.lower())


def _tokenise(text: str) -> list[str]:
    """Split, remove stopwords, and deduplicate order-preserving."""
    tokens = _normalise(text).split()
    seen: set[str] = set()
    result: list[str] = []
    for t in tokens:
        if t not in _STOPWORDS and t not in seen and len(t) > 1:
            seen.add(t)
            result.append(t)
    return result


def _make_snippet(text: str, tokens: list[str], window: int = 160) -> str:
    """
    Extract the best snippet from *text* that contains the most query tokens,
    then bold each occurrence of a token within the snippet.

    Returns plain text (with **bold** markers) of at most *window* characters.
    """
    lower = text.lower()
    # Find the earliest position of any token
    best_pos = len(text)
    for tok in tokens:
        idx = lower.find(tok)
        if idx != -1 and idx < best_pos:
            best_pos = idx

    # Extend window around best_pos
    start = max(0, best_pos - 30)
    end = min(len(text), start + window)
    snippet = ("..." if start > 0 else "") + text[start:end] + ("..." if end < len(text) else "")

    # Bold matched tokens within snippet (case-insensitive)
    for tok in sorted(tokens, key=len, reverse=True):  # longest first to avoid partial overlap
        snippet = re.sub(
            rf"(?i)({re.escape(tok)})",
            r"**\1**",
            snippet,
        )

    return snippet


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------

def _score_entry(
    entry: _IndexEntry,
    query_lower: str,
    tokens: list[str],
) -> float:
    """Return a raw relevance score for one index entry."""
    title: str = str(entry["title"]).lower()
    description: str = str(entry["description"]).lower()
    keywords: list[str] = [str(k).lower() for k in entry.get("keywords", [])]
    keywords_text: str = " ".join(keywords)

    score: float = 0.0

    # Exact phrase matches
    if query_lower in title:
        score += 8.0
    if query_lower in description:
        score += 4.0
    if any(query_lower in kw for kw in keywords):
        score += 6.0

    # Per-token matches
    for tok in tokens:
        if tok in title:
            score += 3.0
        if tok in description:
            score += 1.0
        if any(tok in kw for kw in keywords):
            score += 2.0
        # Prefix / substring match bonus (0.5 per field)
        if any(word.startswith(tok) for word in title.split()):
            score += 0.5
        if any(word.startswith(tok) for word in description.split()):
            score += 0.25
        if any(word.startswith(tok) for word in keywords_text.split()):
            score += 0.25

    # Type-priority boost
    entry_type = str(entry.get("type", "page"))
    score += _TYPE_BOOST.get(entry_type, 0.0)

    return score


# ---------------------------------------------------------------------------
# Pydantic schemas
# ---------------------------------------------------------------------------

class SearchResult(BaseModel):
    title: str
    description: str
    url: str
    type: str
    score: float = Field(..., ge=0.0, le=1.0)
    snippet: str


class SearchResponse(BaseModel):
    results: list[SearchResult]
    total: int
    query: str
    offset: int
    limit: int


# ---------------------------------------------------------------------------
# Route
# ---------------------------------------------------------------------------

@router.get("", response_model=SearchResponse, summary="Full-text search across all content")
@limiter.limit("30/minute")
async def search(
    request: Request,
    q: Annotated[str, Query(min_length=1, max_length=200, description="Search query")] = "",
    limit: Annotated[int, Query(ge=1, le=50, description="Number of results to return")] = 10,
    offset: Annotated[int, Query(ge=0, description="Number of results to skip")] = 0,
) -> SearchResponse:
    """
    Search across all SIP content: 31 modules, 10 blog posts, 5 tools, 20 pages.

    Scoring uses TF-style token matching with phrase bonuses and type boosts.
    Results are normalised to a 0–1 score and include a highlighted snippet.
    """
    query_stripped = q.strip()

    # Empty or whitespace-only query → return empty
    if not query_stripped:
        return SearchResponse(results=[], total=0, query=q, offset=offset, limit=limit)

    query_lower = _normalise(query_stripped)
    tokens = _tokenise(query_stripped)

    # Score every entry
    scored: list[tuple[float, _IndexEntry]] = []
    for entry in _RAW_INDEX:
        raw = _score_entry(entry, query_lower, tokens)
        if raw > 0:
            scored.append((raw, entry))

    if not scored:
        return SearchResponse(results=[], total=0, query=q, offset=offset, limit=limit)

    # Normalise scores to [0, 1]
    max_score = max(s for s, _ in scored)

    # Sort descending by score
    scored.sort(key=lambda x: x[0], reverse=True)

    total = len(scored)
    page_slice = scored[offset : offset + limit]

    results: list[SearchResult] = []
    for raw_score, entry in page_slice:
        norm_score = round(raw_score / max_score, 4) if max_score > 0 else 0.0
        # Clamp to [0, 1] in case of floating-point edge cases
        norm_score = max(0.0, min(1.0, norm_score))

        description = str(entry["description"])
        snippet = _make_snippet(description, tokens)

        results.append(
            SearchResult(
                title=str(entry["title"]),
                description=description,
                url=str(entry["url"]),
                type=str(entry.get("type", "page")),
                score=norm_score,
                snippet=snippet,
            )
        )

    return SearchResponse(
        results=results,
        total=total,
        query=q,
        offset=offset,
        limit=limit,
    )
